### ISSUE TITLE
セッション管理できるようにする

### ISSUE THREAD

**Issue by putcho01** [HackU-NFP/HackU-NFP-server#6]
mysqlstore
https://github.com/srinathgs/mysqlstore

gorilla/sessions
https://github.com/gorilla/sessions

**Comment by putcho01** [comment]
cookieが使えないからセッション管理うまくいかない
mapを使えばいいのか？

**Comment by putcho01** [comment]
```go
type State struct {
    state string
    name string
    meta  string 
}
stateMap := map[string]*State{}
stateMap["0xu39d3ui"] = &State{state: "hoge", ...}  // 構造体のポインタを格納する

state := stateMap["0xu39d3ui"]
state.token_meta = "huga"
```

**Comment by RU-II** [comment]
画像アプロードはまだ。
![S__324059351](https://user-images.githubusercontent.com/76895201/154719150-49cecae6-9c51-4865-b75a-98d7c48d6818.jpg)
![S__324059353](https://user-images.githubusercontent.com/76895201/154719174-d98503fa-9156-4f46-8103-c0e72d73b095.jpg)
